"""Insult — Shakespearean random abuse generator.

Ported from the legacy ``fun`` plugin's ``Insult`` class. Word lists are
the original ibid set, give or take a couple of typos preserved for
authenticity. Use responsibly.
"""

from __future__ import annotations

import random
from typing import TYPE_CHECKING

from ibid.plugin import Plugin, command

if TYPE_CHECKING:
    from ibid.event import Event

ADJECTIVES = (
    "acidic",
    "antique",
    "artless",
    "base-court",
    "bat-fowling",
    "bawdy",
    "beef-witted",
    "beetle-headed",
    "beslubbering",
    "boil-brained",
    "bootless",
    "churlish",
    "clapper-clawed",
    "clay-brained",
    "clouted",
    "cockered",
    "common-kissing",
    "contemptible",
    "coughed-up",
    "craven",
    "crook-pated",
    "culturally-unsound",
    "currish",
    "dankish",
    "decayed",
    "despicable",
    "dismal-dreaming",
    "dissembling",
    "dizzy-eyed",
    "doghearted",
    "dread-bolted",
    "droning",
    "earth-vexing",
    "egg-sucking",
    "elf-skinned",
    "errant",
    "evil",
    "fat-kidneyed",
    "fawning",
    "fen-sucked",
    "fermented",
    "festering",
    "flap-mouthed",
    "fly-bitten",
    "fobbing",
    "folly-fallen",
    "fool-born",
    "foul",
    "frothy",
    "froward",
    "full-gorged",
    "fulminating",
    "gleeking",
    "goatish",
    "gorbellied",
    "guts-griping",
    "hacked-up",
    "halfbaked",
    "half-faced",
    "hasty-witted",
    "headless",
    "hedge-born",
    "hell-hated",
    "horn-beat",
    "hugger-muggered",
    "humid",
    "idle-headed",
    "ill-borne",
    "ill-breeding",
    "ill-nurtured",
    "impertinent",
    "impure",
    "industrial",
    "inept",
    "infected",
    "infectious",
    "inferior",
    "jarring",
    "knotty-pated",
    "left-over",
    "lewd-minded",
    "loggerheaded",
    "low-quality",
    "lumpish",
    "malodorous",
    "malt-wormy",
    "mammering",
    "mangled",
    "measled",
    "mewling",
    "milk-livered",
    "motley-mind",
    "motley-minded",
    "off-color",
    "onion-eyed",
    "paunchy",
    "penguin-molesting",
    "petrified",
    "pickled",
    "pignutted",
    "plume-plucked",
    "pointy-nosed",
    "porous",
    "pottle-deep",
    "pox-marked",
    "pribbling",
    "puking",
    "puny",
    "railing",
    "rank",
    "reeky",
    "reeling-ripe",
    "roguish",
    "rough-hewn",
    "rude-growing",
    "rude-snouted",
    "rump-fed",
    "ruttish",
    "salty",
    "saucy",
    "saucyspleened",
    "sausage-snorfling",
    "shard-borne",
    "sheep-biting",
    "spam-sucking",
    "spleeny",
    "spongy",
    "spur-galled",
    "squishy",
    "surly",
    "swag-bellied",
    "tardy-gaited",
    "tastless",
    "tempestuous",
    "tepid",
    "thick",
    "tickle-brained",
    "toad-spotted",
    "tofu-nibbling",
    "tottering",
    "uninspiring",
    "unintelligent",
    "unmuzzled",
    "unoriginal",
    "urchin-snouted",
    "vain",
    "vapid",
    "vassal-willed",
    "venomed",
    "villainous",
    "warped",
    "wayward",
    "weasel-smelling",
    "weather-bitten",
    "weedy",
    "wretched",
    "yeasty",
)

COLLECTIONS = (
    "accumulation",
    "ass-full",
    "assload",
    "bag",
    "bucket",
    "coagulation",
    "enema-bucketful",
    "gob",
    "half-mouthful",
    "heap",
    "mass",
    "mound",
    "ooze",
    "petrification",
    "pile",
    "plate",
    "puddle",
    "quart",
    "stack",
    "thimbleful",
    "tongueful",
)

NOUNS = (
    "apple-john",
    "baggage",
    "barnacle",
    "bladder",
    "boar-pig",
    "bugbear",
    "bum-bailey",
    "canker-blossom",
    "clack-dish",
    "clotpole",
    "coxcomb",
    "codpiece",
    "death-token",
    "dewberry",
    "flap-dragon",
    "flax-wench",
    "flirt-gill",
    "foot-licker",
    "fustilarian",
    "giglet",
    "gudgeon",
    "haggard",
    "harpy",
    "hedge-pig",
    "horn-beast",
    "hugger-mugger",
    "jolthead",
    "lewdster",
    "lout",
    "maggot-pie",
    "malt-worm",
    "mammet",
    "measle",
    "minnow",
    "miscreant",
    "moldwarp",
    "mumble-news",
    "nut-hook",
    "pigeon-egg",
    "pignut",
    "puttock",
    "pumpion",
    "ratsbane",
    "scut",
    "skainsmate",
    "strumpet",
    "varlet",
    "vassal",
    "whey-face",
    "wagtail",
)

PLURAL_NOUNS = (
    "anal warts",
    "armadillo snouts",
    "bat toenails",
    "bug spit",
    "buzzard gizzards",
    "cat bladders",
    "cat hair",
    "cat-hair-balls",
    "chicken piss",
    "cold sores",
    "craptacular carpet droppings",
    "dog balls",
    "dog vomit",
    "dung",
    "eel ooze",
    "entrails",
    "fat-woman's stomach-bile",
    "fish heads",
    "guano",
    "gunk",
    "jizzum",
    "pods",
    "pond scum",
    "poop",
    "poopy",
    "pus",
    "rat-farts",
    "rat retch",
    "red dye number-9",
    "seagull puke",
    "slurpee-backwash",
    "snake assholes",
    "snake bait",
    "snake snot",
    "squirrel guts",
    "Stimpy-drool",
    "Sun IPC manuals",
    "toxic waste",
    "urine samples",
    "waffle-house grits",
    "yoo-hoo",
)


def article(word: str) -> str:
    """Choose ``a``/``an`` for ``word``."""
    return "an" if word[:1].lower() in "aehiou" else "a"


def build_insult(target: str) -> str:
    """Generate one insult line directed at ``target``."""
    template = random.choice(
        [
            "{target}, thou {adj1}, {adj2} {noun}",
            "{target} is nothing but {article} {adjp} {collection} of {adj1} {plnoun}",
        ]
    )
    adjp = random.choice(ADJECTIVES)
    return template.format(
        target=target,
        adj1=random.choice(ADJECTIVES),
        adj2=random.choice(ADJECTIVES),
        adjp=adjp,
        article=article(adjp),
        collection=random.choice(COLLECTIONS),
        noun=random.choice(NOUNS),
        plnoun=random.choice(PLURAL_NOUNS),
    )


class Insult(Plugin):
    name = "insult"

    @command("insult", "flame")
    async def insult(self, event: Event, args: str) -> None:
        """insult <person> — sling some Shakespearean abuse."""
        target = args.strip()
        if not target:
            await event.reply("who? usage: insult <person>")
            return
        await event.reply(build_insult(target), address=False)


PLUGINS = [Insult]
